---
- name: Configure TFTP on Debian Systems
  hosts: debian_servers
  become: true

  tasks:
    - name: Install TFTP server
      apt:
        name: tftpd-hpa
        state: present

    - name: Ensure TFTP service is enabled and running
      systemd:
        name: tftpd-hpa
        state: started
        enabled: yes


